image: maven:3.8.4-jdk-11

stages:
  - test

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - export LANG=C.UTF-8

test_job:
  stage: test
  script:
    - echo "Current directory:"
    - pwd
    - echo "List of files:"
    - ls -la
    - mvn clean verify
  artifacts:
    paths:
      - target/site/serenity
    expire_in: 1 week
