stages:
  - test

api-tests:
  image: maven:3.9.6-eclipse-temurin-17
  stage: test
  script:
    - cd leasePlan
    - mvn clean verify
  artifacts:
    when: always
    paths:
      - leasePlan/target/site/serenity
    reports:
      junit: leasePlan/target/site/serenity/serenity-junit.xml

